import { doctors } from '../../data/mock.js'

export const adminSpecialties = ['Tất cả chuyên khoa', 'Nội tổng quát', 'Tim mạch', 'Răng Hàm Mặt', 'Chỉnh hình']
export const adminClinics = ['Tất cả phòng khám', 'Phòng khám Đa khoa Tâm An', 'Phòng khám Tim mạch An Bình', 'MedCare Family Clinic']
export const adminStatuses = ['Tất cả trạng thái', 'Đang làm việc', 'Đang khám', 'Nghỉ phép', 'Tạm ngưng']

const doctorMetadata = [
  {
    clinic: 'Phòng khám Đa khoa Tâm An',
    clinicRoom: 'Phòng 102',
    email: 'minh.nguyen@medconsult.vn',
    status: 'Đang làm việc',
    rating: 4.9,
    reviews: 430,
    today: 8,
    experience: 12,
    consultations: 1240,
    satisfaction: 96,
    monthCases: 26,
    skills: ['Nội khoa', 'Hô hấp', 'Tiêu hóa'],
    degree: 'Bác sĩ Chuyên khoa I',
    certificates: 'Chứng chỉ hành nghề khám chữa bệnh nội khoa',
    languages: 'Tiếng Việt, Tiếng Anh',
    services: 'Khám nội tổng quát, tư vấn hô hấp, theo dõi bệnh mạn tính',
    gender: 'Nam',
    address: 'Quận 3, TP. Hồ Chí Minh',
    updated: '12 phút trước',
    updatedRank: 4,
  },
  {
    clinic: 'Phòng khám Tim mạch An Bình',
    clinicRoom: 'Phòng 201',
    email: 'hoa.tran@medconsult.vn',
    status: 'Đang khám',
    rating: 4.8,
    reviews: 382,
    today: 7,
    experience: 10,
    consultations: 980,
    satisfaction: 94,
    monthCases: 22,
    skills: ['Tim mạch', 'Điện tim', 'Tăng huyết áp'],
    degree: 'Thạc sĩ Y khoa',
    certificates: 'Chứng chỉ chuyên khoa tim mạch can thiệp',
    languages: 'Tiếng Việt, Tiếng Anh',
    services: 'Khám tim mạch, đo điện tim, theo dõi huyết áp',
    gender: 'Nữ',
    address: 'Bình Thạnh, TP. Hồ Chí Minh',
    updated: '35 phút trước',
    updatedRank: 3,
  },
  {
    clinic: 'MedCare Family Clinic',
    clinicRoom: 'Phòng 305',
    email: 'anh.le@medconsult.vn',
    status: 'Nghỉ phép',
    rating: 4.7,
    reviews: 268,
    today: 4,
    experience: 8,
    consultations: 760,
    satisfaction: 92,
    monthCases: 18,
    skills: ['Răng Hàm Mặt', 'Nha khoa', 'Chăm sóc răng'],
    degree: 'Bác sĩ Răng Hàm Mặt',
    certificates: 'Chứng chỉ điều trị nha khoa tổng quát',
    languages: 'Tiếng Việt',
    services: 'Khám răng, tư vấn chăm sóc răng miệng',
    gender: 'Nam',
    address: 'Quận 1, TP. Hồ Chí Minh',
    updated: 'Hôm qua',
    updatedRank: 2,
  },
  {
    clinic: 'Phòng khám Đa khoa Tâm An',
    clinicRoom: 'Phòng 108',
    email: 'tuan.pham@medconsult.vn',
    status: 'Tạm ngưng',
    rating: 4.6,
    reviews: 190,
    today: 3,
    experience: 14,
    consultations: 640,
    satisfaction: 90,
    monthCases: 16,
    skills: ['Chỉnh hình', 'Cơ xương khớp', 'Vật lý trị liệu'],
    degree: 'Bác sĩ Chuyên khoa II',
    certificates: 'Chứng chỉ phẫu thuật chỉnh hình',
    languages: 'Tiếng Việt, Tiếng Pháp',
    services: 'Khám cơ xương khớp, tư vấn chỉnh hình',
    gender: 'Nam',
    address: 'Quận 3, TP. Hồ Chí Minh',
    updated: '2 ngày trước',
    updatedRank: 1,
  },
]

export const adminDoctors = doctors.map((doctor, index) => ({
  ...doctor,
  ...doctorMetadata[index],
}))
